const selectValues = {
  anime: {
    order_by: [
      { value: 'title', children: 'Title' },
      { value: 'score', children: 'Score' },
      { value: 'scored_by', children: 'Scored by' },
      { value: 'popularity', children: 'Popularity' },
      { value: 'members', children: 'Members' },
      { value: 'favorites', children: 'Favorites' },
      { value: 'rank', children: 'Rank' },
      { value: 'type', children: 'Type' },
      { value: 'rating', children: 'Rating' },
      { value: 'episodes', children: 'Episodes' },
      { value: 'start_date', children: 'Start date' },
      { value: 'end_date', children: 'End date' },
    ],
    sort: [{ value: 'desc', children: 'Descending' }],
    type: [
      { value: 'tv', children: 'Serie' },
      { value: 'movie', children: 'Movie' },
      { value: 'ova', children: 'OVA' },
      { value: 'special', children: 'Special' },
      { value: 'ona', children: 'ONA' },
      { value: 'music', children: 'Music' },
    ],
    scoreMin: [
      { value: '1', children: '1' },
      { value: '2', children: '2' },
      { value: '3', children: '3' },
      { value: '4', children: '4' },
      { value: '5', children: '5' },
      { value: '6', children: '6' },
      { value: '7', children: '7' },
      { value: '8', children: '8' },
      { value: '9', children: '9' },
    ],
    status: [
      { value: 'airing', children: 'Airing' },
      { value: 'complete', children: 'Complete' },
      { value: 'upcoming', children: 'Upcoming' },
    ],
    rating: [
      { value: 'g', children: 'G - All Ages' },
      { value: 'pg', children: 'PG - Children' },
      { value: 'pg13', children: 'PG-13 - Teens 13 or older' },
      { value: 'r17', children: 'R - 17+ (violence & profanity)' },
      { value: 'r', children: 'R+ - Mild Nudity' },
      { value: 'rx', children: 'Rx - Hentai' },
    ],
  },

  manga: {
    order_by: [
      { value: 'title', children: 'Title' },
      { value: 'score', children: 'Score' },
      { value: 'scored_by', children: 'Scored by' },
      { value: 'popularity', children: 'Popularity' },
      { value: 'members', children: 'Members' },
      { value: 'favorites', children: 'Favorites' },
      { value: 'rank', children: 'Rank' },
      { value: 'volumes', children: 'Volumes' },
      { value: 'chapters', children: 'Chapters' },
      { value: 'start_date', children: 'Start date' },
      { value: 'end_date', children: 'End date' },
    ],
    sort: [{ value: 'desc', children: 'Descending' }],
    type: [
      { value: 'manga', children: 'Manga' },
      { value: 'novel', children: 'Novel' },
      { value: 'lightnovel', children: 'Lightnovel' },
      { value: 'oneshot', children: 'Oneshot' },
      { value: 'doujin', children: 'Doujin' },
      { value: 'manhwa', children: 'Manhwa' },
      { value: 'manhua', children: 'Manhua' },
    ],
    scoreMin: [
      { value: '1', children: '1' },
      { value: '2', children: '2' },
      { value: '3', children: '3' },
      { value: '4', children: '4' },
      { value: '5', children: '5' },
      { value: '6', children: '6' },
      { value: '7', children: '7' },
      { value: '8', children: '8' },
      { value: '9', children: '9' },
    ],
    status: [
      { value: 'publishing', children: 'Publishing' },
      { value: 'complete', children: 'Complete' },
      { value: 'hiatus', children: 'Hiatus' },
      { value: 'discontinued', children: 'Discontinued' },
      { value: 'upcoming', children: 'Upcoming' },
    ],
  },
}

export default selectValues
